Exercice 1 : Création et manipulation de réseaux
Instructions
Créez un tableau NumPy 1D contenant des nombres de 0 à 9.

In [30]:
import pandas as pd
import numpy as np
from numpy import random

array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Exercice 2 : Conversion de type et opérations sur l’array
Instructions
Convertissez une liste[3.14, 2.17, 0, 1, 2] en tableau NumPy et convertissez son type de données en entier.

In [6]:
liste1 = [3.14, 2.17, 0, 1, 2]
liste1 = np.array(liste1)
liste1.astype(int)


array([3, 2, 0, 1, 2])

Exercice 3 : Travailler avec des réseaux multidimensionnels
Instructions
Créez un tableau NumPy 3x3 avec des valeurs allant de 1 à 9.

In [10]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Exercice 4 : Créer un tableau multidimensionnel avec des nombres aléatoires
Instructions
Créez un tableau NumPy 2D de formes (4, 5) remplies de nombres aléatoires.

In [25]:
array2 = np.round(np.random.rand(4,5), 2)
array2

array([[0.29, 0.65, 0.91, 0.26, 0.64],
       [0.56, 0.07, 0.33, 0.47, 0.07],
       [0.3 , 0.77, 0.09, 0.26, 0.9 ],
       [0.09, 0.77, 0.29, 0.24, 0.68]])

Exercice 5 : Indexation des tableaux
Instructions
Sélectionnez la deuxième ligne parmi un tableau NumPy 2D donné.

In [27]:
array3 = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print(f"La deuxièm ligne du tableau : {array3[1, :]}")

La deuxièm ligne du tableau : [20 21 22 23 24]


Exercice 6 : Inverser les éléments
Instructions
Inversez l’ordre des éléments dans un tableau NumPy 1D donné (le premier élément devient le dernier)

In [29]:
array4 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
array4[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Exercice 7 : Matrice d’identité
Instructions
Créez une matrice d’identité 4x4 en utilisant NumPy.

In [31]:
identite = np.identity(4)
identite

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Exercice 8 : Fonctions agrégées simples
Instructions
Trouvez la somme et la moyenne d’un tableau 1D donné.


In [44]:
somme = np.sum(array)
moyenne = np.mean(array)
print(f"La somme du tableau array1 est : {somme}. \nEt la moyenne est {moyenne}")

La somme du tableau array1 est : 45. 
Et la moyenne est 4.5


Exercice 9 : Créer un tableau et changer sa structure
Instructions
Créer un tableau NumPy avec des éléments allant de 1 à 20 ; Puis remodelez-le en une matrice 4x5.

In [45]:
array6 = np.arange(1, 21)
array6.reshape(4, 5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

Exercice 10 : Sélection conditionnelle des valeurs
Instructions
Extraire tous les nombres impairs d’un tableau NumPy donné.

In [47]:
array[(array % 2 )!=0]

array([1, 3, 5, 7, 9])